# Encoding: UTF-8
#
# Cookbook Name:: kitchen-localhost-test
# Recipe:: create_file
#

require 'tmpdir'

file File.join(Dir.tmpdir, 'testing_kitchen_localhost') do
  content 'This file generated by Chef'
  action :create
end
