# Encoding: UTF-8
#
# Cookbook Name:: kitchen-localhost-test
# Recipe:: default
#

directory '/tmp'

file ::File.join('/tmp', node['kitchen_localhost_test']['test_file']) do
  content 'This file generated by Chef'
end
