# Encoding: UTF-8

require 'tmpdir'
require 'spec_helper'

describe file("#{Dir.tmpdir}/testing_kitchen_localhost") do
  it 'exists' do
    expect(subject).to be_file
  end

  it 'contains the expected content' do
    expect(subject.content).to match('This file generated by Chef')
  end
end
